package com.schmarrntisch.appbase.config

const val FREQUENCY_VOTING = 2
const val FREQUENCY_COUNTING = 2
const val FREQUENCY_CONDITION = 2
const val FREQUENCY_GROUPACTION = 2
const val FREQUENCY_GROUPVIRUS = 2
const val FREQUENCY_CARDSPEED = 2
const val FREQUENCY_CARDPARTNER = 2
const val FREQUENCY_PARTNERACTION = 2
const val FREQUENCY_RULE = 2
const val FREQUENCY_PLAYERACTION = 2
const val FREQUENCY_TABU = 2
const val FREQUENCY_VIRUS = 2
const val FREQUENCY_TONGUETWISTER = 2
const val FREQUENCY_SPEED = 2
const val FREQUENCY_BUSFAHRER = 2